name: CI - Iris Classifier

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest -q

    - name: Run training and generate model + metrics
      run: python train.py --model-path model.joblib --metrics-path metrics.csv

    - name: Upload metrics for review
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: training-metrics
        path: metrics.csv
